[project]
name = "compnet"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "attrs>=25.1.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "tqdm>=4.67.1",
]

[tool.ruff]
fix = true
lint.select = [
    "I001",
    "F401",
]
